dist: xenial
language: python
python: 3.7
sudo: true

before_install:
  - sudo apt-get update

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_extended_0.58.3_Linux-64bit.deb && sudo dpkg -i hugo_extended*.deb
  - sudo apt-get install -y jing bibutils

script:
  - make check site
