name: preview

on:
  push:
    branches:
    - '*'
    - '!master'

jobs:
  preview:
    runs-on: ubuntu-20.04
    steps:
    - name: install hugo
      run: wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_extended_0.58.3_Linux-64bit.deb && sudo dpkg -i hugo_extended*.deb
    - name: update
      run: sudo apt-get update
    - name: install other deps
      run: sudo apt-get install -y jing bibutils openssh-client rsync libyaml-dev libpython3.8-dev
    - name: dump secret key
      env:
        SSH_KEY: ${{ secrets.PUBLISH_SSH_KEY }}
      run: |
        mkdir -p $HOME/.ssh/
        echo "$SSH_KEY" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
    - uses: actions/checkout@v1
    - name: extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: build
      shell: bash
      env:
        ANTHOLOGY_PREFIX: https://www.aclweb.org/anthology/previews/${{ steps.extract_branch.outputs.branch }}
      run: |
        make ANTHOLOGY_PREFIX=$ANTHOLOGY_PREFIX NOBIB=true check site
    - name: preview
      env:
        PUBLISH_TARGET: aclwebor@50.87.169.12:anthology-static/previews/${{ steps.extract_branch.outputs.branch }}
      run: |
        echo "Mirroring branch to $PUBLISH_TARGET"
        pwd
        ls
        ls /home/runner/work/acl-anthology/
        ls /home/runner/work/acl-anthology/acl-anthology
        ls /home/runner/work/acl-anthology/acl-anthology/build
        echo "Command: rsync -aze "ssh -o StrictHostKeyChecking=accept-new" build/anthology/ $PUBLISH_TARGET"
