name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - name: install hugo
      run: wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_extended_0.58.3_Linux-64bit.deb && sudo dpkg -i hugo_extended*.deb
    - name: update
      run: sudo apt-get update
    - name: install other deps
      run: sudo apt-get install -y jing bibutils openssh-client rsync libyaml-dev libpython3.8-dev
    - name: dump secret key
      env:
        SSH_KEY: ${{ secrets.PUBLISH_SSH_KEY }}
      run: |
        mkdir -p $HOME/.ssh/
        echo "$SSH_KEY" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
    - uses: actions/checkout@v1
    - name: build
      env:
        ANTHOLOGY_PREFIX: https://www.aclweb.org/anthology
      run: |
        make ANTHOLOGY_PREFIX=$ANTHOLOGY_PREFIX check site
    - name: publish
      env:
        PUBLISH_TARGET: 50.87.169.12:anthology-static
      run: |
        rsync -aze "ssh -o StrictHostKeyChecking=accept-new" --delete build/anthology/ $PUBLISH_TARGET
