name: publish

on:
  push:
    branch:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install hugo
      run: wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_extended_0.58.3_Linux-64bit.deb && sudo dpkg -i hugo_extended*.deb
    - name: install other deps
      run: sudo apt-get install -y jing bibutils openssh-client rsync libyaml-dev libpython3.7-dev
    - name: dump secret key
      env:
        SSH_KEY: ${{ secrets.PUBLISH_SSH_KEY }}
      run: |
        mkdir -p $HOME/.ssh/
        echo "$SSH_KEY" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
    - uses: actions/checkout@v1
    - name: build
      env:
        ANTHOLOGYHOST: ${{ secrets.PUBLISH_ANTHOLOGYHOST }}
      run: |
        make ANTHOLOGYHOST=$ANTHOLOGYHOST check site
    - name: publish
      env:
        PUBLISH_TARGET: ${{ secrets.PUBLISH_TARGET }}
      run: |
        rsync -aze "ssh -o StrictHostKeyChecking=accept-new" --delete build/anthology/ $PUBLISH_TARGET
