name: remove-preview

on:
  delete:
    branches:
    - '*'
    - '!master'

jobs:
  remove-preview:
    runs-on: ubuntu-20.04
    steps:
    - name: update
      run: sudo apt-get update
    - name: install other deps
      run: sudo apt-get install -y openssh-client rsync
    - name: dump secret key
      env:
        SSH_KEY: ${{ secrets.PUBLISH_SSH_KEY }}
      run: |
        mkdir -p $HOME/.ssh/
        echo "$SSH_KEY" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
    - uses: actions/checkout@v1
    - name: extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: remove-preview
      env:
        BRANCH: ${{ steps.extract_branch.outputs.branch }}
      run: |
        echo "Would delete branch ${BRANCH}"
        echo ssh -o StrictHostKeyChecking=accept-new rm -rf /var/www/aclanthology.org/previews/${BRANCH}
